package beat;

public class MusicBeat {
	BeatPlay[] beats;

	public BeatPlay[] happy_Life(String difficulty) {
		int startTime = 1350 - Main.REACH_TIME * 1000;
		int gap = 1200;
		if (difficulty.equals("Easy")) {
			beats = new BeatPlay[] { new BeatPlay(startTime + gap * 0, "S"), new BeatPlay(startTime + gap * 1, "J"),
					new BeatPlay(startTime + gap * 2, "D"), new BeatPlay(startTime + gap * 3, "S"),
					new BeatPlay(startTime + gap * 4, "F"), new BeatPlay(startTime + gap * 5, "L"),
					new BeatPlay(startTime + gap * 6, "J"), new BeatPlay(startTime + gap * 7, "K"),
					new BeatPlay(startTime + gap * 8, "D"), new BeatPlay(startTime + gap * 9, "D"),
					new BeatPlay(startTime + gap * 10, "S"), new BeatPlay(startTime + gap * 11, "F"),
					new BeatPlay(startTime + gap * 12, "L"), new BeatPlay(startTime + gap * 13, "J"),
					new BeatPlay(startTime + gap * 14, "K"), new BeatPlay(startTime + gap * 15, "K"),
					new BeatPlay(startTime + gap * 16, "D"), new BeatPlay(startTime + gap * 17, "S"),
					new BeatPlay(startTime + gap * 18, "F"), new BeatPlay(startTime + gap * 19, "L"),
					new BeatPlay(startTime + gap * 20, "J"), new BeatPlay(startTime + gap * 21, "K"),
					new BeatPlay(startTime + gap * 22, "J"), new BeatPlay(startTime + gap * 23, "D"),
					new BeatPlay(startTime + gap * 24, "S"), new BeatPlay(startTime + gap * 25, "F"),
					new BeatPlay(startTime + gap * 26, "L"), new BeatPlay(startTime + gap * 27, "J"),
					new BeatPlay(startTime + gap * 28, "K"), new BeatPlay(startTime + gap * 29, "L"),
					new BeatPlay(startTime + gap * 30, "D"), new BeatPlay(startTime + gap * 31, "S"),
					new BeatPlay(startTime + gap * 32, "F"), new BeatPlay(startTime + gap * 33, "L"),
					new BeatPlay(startTime + gap * 34, "J"), new BeatPlay(startTime + gap * 35, "K"),
					new BeatPlay(startTime + gap * 36, "F"), new BeatPlay(startTime + gap * 37, "D"),
					new BeatPlay(startTime + gap * 38, "S"), new BeatPlay(startTime + gap * 39, "F"),
					new BeatPlay(startTime + gap * 40, "L"), new BeatPlay(startTime + gap * 41, "J"),
					new BeatPlay(startTime + gap * 42, "K"), new BeatPlay(startTime + gap * 43, "S"),
					new BeatPlay(startTime + gap * 44, "D"), new BeatPlay(startTime + gap * 45, "S"),
					new BeatPlay(startTime + gap * 46, "F"), new BeatPlay(startTime + gap * 47, "L"),
					new BeatPlay(startTime + gap * 48, "J"), new BeatPlay(startTime + gap * 49, "K"),
					new BeatPlay(startTime + gap * 50, "F"), new BeatPlay(startTime + gap * 51, "D"),
					new BeatPlay(startTime + gap * 52, "S"), new BeatPlay(startTime + gap * 53, "F"),
					new BeatPlay(startTime + gap * 54, "L"), new BeatPlay(startTime + gap * 56, "L") };

			return beats;
		}

		else if (difficulty.equals("Hard")) {
			beats = new BeatPlay[] { new BeatPlay(startTime + gap * 0, "L"), new BeatPlay(startTime + gap * 1, "S"),
					new BeatPlay(startTime + gap * 2, "D"), new BeatPlay(startTime + gap * 2, "K"),
					new BeatPlay(startTime + gap * 3, "S"), new BeatPlay(startTime + gap * 3, "F"),
					new BeatPlay(startTime + gap * 4, "J"), new BeatPlay(startTime + gap * 4, "F"),
					new BeatPlay(startTime + gap * 5, "L"), new BeatPlay(startTime + gap * 6, "J"),
					new BeatPlay(startTime + gap * 7, "K"), new BeatPlay(startTime + gap * 8, "S"),
					new BeatPlay(startTime + gap * 9, "D"), new BeatPlay(startTime + gap * 10, "S"),
					new BeatPlay(startTime + gap * 11, "F"), new BeatPlay(startTime + gap * 12, "L"),
					new BeatPlay(startTime + gap * 12, "S"), new BeatPlay(startTime + gap * 13, "J"),
					new BeatPlay(startTime + gap * 14, "K"), new BeatPlay(startTime + gap * 15, "J"),
					new BeatPlay(startTime + gap * 16, "D"), new BeatPlay(startTime + gap * 17, "S"),
					new BeatPlay(startTime + gap * 18, "F"), new BeatPlay(startTime + gap * 18, "S"),
					new BeatPlay(startTime + gap * 18, "J"), new BeatPlay(startTime + gap * 19, "L"),
					new BeatPlay(startTime + gap * 20, "J"), new BeatPlay(startTime + gap * 21, "K"),
					new BeatPlay(startTime + gap * 22, "S"), new BeatPlay(startTime + gap * 23, "D"),
					new BeatPlay(startTime + gap * 24, "S"), new BeatPlay(startTime + gap * 25, "F"),
					new BeatPlay(startTime + gap * 26, "L"), new BeatPlay(startTime + gap * 27, "S"),
					new BeatPlay(startTime + gap * 27, "D"), new BeatPlay(startTime + gap * 27, "F"),
					new BeatPlay(startTime + gap * 27, "J"), new BeatPlay(startTime + gap * 27, "K"),
					new BeatPlay(startTime + gap * 27, "L"), new BeatPlay(startTime + gap * 28, "K"),
					new BeatPlay(startTime + gap * 29, "F"), new BeatPlay(startTime + gap * 30, "D"),
					new BeatPlay(startTime + gap * 31, "S"), new BeatPlay(startTime + gap * 32, "F"),
					new BeatPlay(startTime + gap * 33, "L"), new BeatPlay(startTime + gap * 33, "S"),
					new BeatPlay(startTime + gap * 34, "J"), new BeatPlay(startTime + gap * 34, "D"),
					new BeatPlay(startTime + gap * 34, "S"), new BeatPlay(startTime + gap * 34, "F"),
					new BeatPlay(startTime + gap * 35, "K"), new BeatPlay(startTime + gap * 35, "F"),
					new BeatPlay(startTime + gap * 35, "L"), new BeatPlay(startTime + gap * 36, "D"),
					new BeatPlay(startTime + gap * 37, "D"), new BeatPlay(startTime + gap * 38, "S"),
					new BeatPlay(startTime + gap * 39, "F"), new BeatPlay(startTime + gap * 39, "J"),
					new BeatPlay(startTime + gap * 40, "L"), new BeatPlay(startTime + gap * 41, "J"),
					new BeatPlay(startTime + gap * 42, "K"), new BeatPlay(startTime + gap * 43, "S"),
					new BeatPlay(startTime + gap * 44, "D"), new BeatPlay(startTime + gap * 45, "S"),
					new BeatPlay(startTime + gap * 46, "F"), new BeatPlay(startTime + gap * 47, "L"),
					new BeatPlay(startTime + gap * 47, "J"), new BeatPlay(startTime + gap * 47, "F"),
					new BeatPlay(startTime + gap * 48, "J"), new BeatPlay(startTime + gap * 49, "K"),
					new BeatPlay(startTime + gap * 50, "S"), new BeatPlay(startTime + gap * 51, "D"),
					new BeatPlay(startTime + gap * 52, "S"), new BeatPlay(startTime + gap * 53, "F"),
					new BeatPlay(startTime + gap * 54, "S"), new BeatPlay(startTime + gap * 54, "D"),
					new BeatPlay(startTime + gap * 54, "F"), new BeatPlay(startTime + gap * 54, "L"),
					new BeatPlay(startTime + gap * 54, "J"), new BeatPlay(startTime + gap * 54, "K"),
					new BeatPlay(startTime + gap * 56, "J"), };

			return beats;
		} else
			return null;
	}

	public BeatPlay[] chilling(String difficulty) {
		int startTime = 0;
		int gap = 125;
		if (difficulty.equals("Easy")) {
			beats = new BeatPlay[] { new BeatPlay(startTime, "S"), new BeatPlay(startTime + gap * 3, "F"),
					new BeatPlay(startTime + gap * 6, "S"), new BeatPlay(startTime + gap * 9, "F"),
					new BeatPlay(startTime + gap * 12, "D"), new BeatPlay(startTime + gap * 15, "J"),
					new BeatPlay(startTime + gap * 18, "L"), new BeatPlay(startTime + gap * 21, "J"),
					new BeatPlay(startTime + gap * 24, "L"), new BeatPlay(startTime + gap * 27, "K"),
					new BeatPlay(startTime + gap * 30, "D"), new BeatPlay(startTime + gap * 33, "K"),
					new BeatPlay(startTime + gap * 36, "D"), new BeatPlay(startTime + gap * 39, "S"),
					new BeatPlay(startTime + gap * 42, "F"), new BeatPlay(startTime + gap * 45, "S"),
					new BeatPlay(startTime + gap * 48, "F"), new BeatPlay(startTime + gap * 51, "L"),
					new BeatPlay(startTime + gap * 54, "J"), new BeatPlay(startTime + gap * 57, "L"),
					new BeatPlay(startTime + gap * 60, "J"), new BeatPlay(startTime + gap * 63, "L"),
					new BeatPlay(startTime + gap * 66, "D"), new BeatPlay(startTime + gap * 69, "D"),
					new BeatPlay(startTime + gap * 72, "K"), new BeatPlay(startTime + gap * 75, "J"),
					new BeatPlay(startTime + gap * 78, "S"), new BeatPlay(startTime + gap * 78, "F"),
					new BeatPlay(startTime + gap * 81, "J"), new BeatPlay(startTime + gap * 81, "L"),
					new BeatPlay(startTime + gap * 84, "S"), new BeatPlay(startTime + gap * 84, "F"),
					new BeatPlay(startTime + gap * 87, "J"), new BeatPlay(startTime + gap * 87, "L"),
					new BeatPlay(startTime + gap * 90, "F"), new BeatPlay(startTime + gap * 93, "S"),
					new BeatPlay(startTime + gap * 96, "F"), new BeatPlay(startTime + gap * 99, "S"),
					new BeatPlay(startTime + gap * 102, "F"), new BeatPlay(startTime + gap * 105, "K"),
					new BeatPlay(startTime + gap * 108, "S"), new BeatPlay(startTime + gap * 108, "F"),
					new BeatPlay(startTime + gap * 111, "J"), new BeatPlay(startTime + gap * 111, "L"),
					new BeatPlay(startTime + gap * 114, "S"), new BeatPlay(startTime + gap * 114, "F"),
					new BeatPlay(startTime + gap * 117, "J"), new BeatPlay(startTime + gap * 117, "L"),
					new BeatPlay(startTime + gap * 120, "D"), new BeatPlay(startTime + gap * 123, "J"),
					new BeatPlay(startTime + gap * 126, "L"), new BeatPlay(startTime + gap * 129, "J"),
					new BeatPlay(startTime + gap * 132, "L"), new BeatPlay(startTime + gap * 135, "D"),
					new BeatPlay(startTime + gap * 137, "S"), new BeatPlay(startTime + gap * 139, "F"),
					new BeatPlay(startTime + gap * 141, "S"), new BeatPlay(startTime + gap * 143, "F"),
					new BeatPlay(startTime + gap * 145, "J"), new BeatPlay(startTime + gap * 147, "L"),
					new BeatPlay(startTime + gap * 149, "J"), new BeatPlay(startTime + gap * 151, "L"),
					new BeatPlay(startTime + gap * 153, "D"), new BeatPlay(startTime + gap * 155, "S"),
					new BeatPlay(startTime + gap * 157, "F"), new BeatPlay(startTime + gap * 159, "S"),
					new BeatPlay(startTime + gap * 161, "F"), new BeatPlay(startTime + gap * 163, "J"),
					new BeatPlay(startTime + gap * 165, "L"), new BeatPlay(startTime + gap * 167, "J"),
					new BeatPlay(startTime + gap * 169, "L"), new BeatPlay(startTime + gap * 171, "S"),
					new BeatPlay(startTime + gap * 173, "D"), new BeatPlay(startTime + gap * 175, "K"),
					new BeatPlay(startTime + gap * 177, "D"), new BeatPlay(startTime + gap * 179, "K"),
					new BeatPlay(startTime + gap * 181, "K"), new BeatPlay(startTime + gap * 183, "S"),
					new BeatPlay(startTime + gap * 185, "F"), new BeatPlay(startTime + gap * 187, "S"),
					new BeatPlay(startTime + gap * 189, "F"), new BeatPlay(startTime + gap * 191, "D"),
					new BeatPlay(startTime + gap * 193, "J"), new BeatPlay(startTime + gap * 195, "L"),
					new BeatPlay(startTime + gap * 197, "J"), new BeatPlay(startTime + gap * 199, "L"),
					new BeatPlay(startTime + gap * 201, "S"), new BeatPlay(startTime + gap * 203, "D"),
					new BeatPlay(startTime + gap * 205, "K"), new BeatPlay(startTime + gap * 207, "D"),
					new BeatPlay(startTime + gap * 209, "K"), new BeatPlay(startTime + gap * 211, "K"),
					new BeatPlay(startTime + gap * 213, "S"), new BeatPlay(startTime + gap * 213, "F"),
					new BeatPlay(startTime + gap * 222, "J"), new BeatPlay(startTime + gap * 222, "L"),
					new BeatPlay(startTime + gap * 231, "S"), new BeatPlay(startTime + gap * 231, "F"),
					new BeatPlay(startTime + gap * 240, "J"), new BeatPlay(startTime + gap * 240, "L"),
					new BeatPlay(startTime + gap * 249, "D"), new BeatPlay(startTime + gap * 257, "S"),
					new BeatPlay(startTime + gap * 257, "F"), new BeatPlay(startTime + gap * 266, "J"),
					new BeatPlay(startTime + gap * 266, "L"), new BeatPlay(startTime + gap * 275, "S"),
					new BeatPlay(startTime + gap * 275, "F"), new BeatPlay(startTime + gap * 284, "J"),
					new BeatPlay(startTime + gap * 284, "L"), new BeatPlay(startTime + gap * 293, "K"),
					new BeatPlay(startTime + gap * 302, "S"), new BeatPlay(startTime + gap * 311, "F"),
					new BeatPlay(startTime + gap * 320, "J"), new BeatPlay(startTime + gap * 329, "L"),
					new BeatPlay(startTime + gap * 338, "S"), new BeatPlay(startTime + gap * 347, "F"),
					new BeatPlay(startTime + gap * 356, "J"), new BeatPlay(startTime + gap * 365, "L"),
					new BeatPlay(startTime + gap * 374, "D"), new BeatPlay(startTime + gap * 383, "L"),
					new BeatPlay(startTime + gap * 392, "J"), new BeatPlay(startTime + gap * 401, "F"),
					new BeatPlay(startTime + gap * 410, "S"), new BeatPlay(startTime + gap * 419, "L"),
					new BeatPlay(startTime + gap * 428, "J"), new BeatPlay(startTime + gap * 437, "F"),
					new BeatPlay(startTime + gap * 446, "S"), new BeatPlay(startTime + gap * 455, "K"),
					new BeatPlay(startTime + gap * 464, "S"), new BeatPlay(startTime + gap * 473, "L"),
					new BeatPlay(startTime + gap * 482, "F"), new BeatPlay(startTime + gap * 491, "J"),
					new BeatPlay(startTime + gap * 500, "S"), new BeatPlay(startTime + gap * 509, "L"),
					new BeatPlay(startTime + gap * 518, "F"), new BeatPlay(startTime + gap * 527, "J"),
					new BeatPlay(startTime + gap * 536, "L"), new BeatPlay(startTime + gap * 545, "F"),
					new BeatPlay(startTime + gap * 554, "J"), new BeatPlay(startTime + gap * 563, "S"),
					new BeatPlay(startTime + gap * 572, "L"), new BeatPlay(startTime + gap * 581, "F"),
					new BeatPlay(startTime + gap * 590, "J"), new BeatPlay(startTime + gap * 599, "S"),
					new BeatPlay(startTime + gap * 608, "L"),  };
			return beats;
		}

		else if (difficulty.equals("Hard")) {
			beats = new BeatPlay[] { 
					new BeatPlay(startTime, "S"), new BeatPlay(startTime + gap * 3, "K"),
					new BeatPlay(startTime + gap * 6, "D"), new BeatPlay(startTime + gap * 9, "J"),
					new BeatPlay(startTime + gap * 12, "L"), new BeatPlay(startTime + gap * 15, "J"),
					new BeatPlay(startTime + gap * 15, "K"), new BeatPlay(startTime + gap * 18, "L"),
					new BeatPlay(startTime + gap * 18, "D"), new BeatPlay(startTime + gap * 21, "J"),
					new BeatPlay(startTime + gap * 21, "F"), 
					new BeatPlay(startTime + gap * 24, "L"), new BeatPlay(startTime + gap * 24, "S"), 
					new BeatPlay(startTime + gap * 27, "K"),
					new BeatPlay(startTime + gap * 30, "D"), new BeatPlay(startTime + gap * 30, "L"),
					new BeatPlay(startTime + gap * 33, "K"), new BeatPlay(startTime + gap * 33, "S"),
					new BeatPlay(startTime + gap * 36, "L"), new BeatPlay(startTime + gap * 39, "S"),
					new BeatPlay(startTime + gap * 42, "F"), new BeatPlay(startTime + gap * 45, "D"),
					new BeatPlay(startTime + gap * 48, "J"), new BeatPlay(startTime + gap * 51, "K"),
					new BeatPlay(startTime + gap * 54, "J"), new BeatPlay(startTime + gap * 54, "K"),
					new BeatPlay(startTime + gap * 57, "S"), new BeatPlay(startTime + gap * 57, "D"), new BeatPlay(startTime + gap * 57, "S"), 
					new BeatPlay(startTime + gap * 63, "L"), 
					new BeatPlay(startTime + gap * 66, "K"), new BeatPlay(startTime + gap * 69, "D"),
					new BeatPlay(startTime + gap * 72, "K"), new BeatPlay(startTime + gap * 75, "J"),
					new BeatPlay(startTime + gap * 78, "S"), new BeatPlay(startTime + gap * 78, "F"),
					new BeatPlay(startTime + gap * 81, "J"), new BeatPlay(startTime + gap * 81, "L"),
					new BeatPlay(startTime + gap * 84, "S"), new BeatPlay(startTime + gap * 84, "F"),
					new BeatPlay(startTime + gap * 87, "J"), new BeatPlay(startTime + gap * 87, "L"),
					new BeatPlay(startTime + gap * 90, "D"), new BeatPlay(startTime + gap * 93, "S"),
					new BeatPlay(startTime + gap * 96, "F"), new BeatPlay(startTime + gap * 99, "S"),
					new BeatPlay(startTime + gap * 102, "F"), new BeatPlay(startTime + gap * 105, "K"),
					new BeatPlay(startTime + gap * 108, "S"), new BeatPlay(startTime + gap * 108, "F"),
					new BeatPlay(startTime + gap * 111, "J"), new BeatPlay(startTime + gap * 111, "L"),
					new BeatPlay(startTime + gap * 114, "S"), new BeatPlay(startTime + gap * 114, "F"),
					new BeatPlay(startTime + gap * 117, "J"), new BeatPlay(startTime + gap * 117, "L"),
					new BeatPlay(startTime + gap * 120, "D"), new BeatPlay(startTime + gap * 123, "J"),
					new BeatPlay(startTime + gap * 126, "L"), new BeatPlay(startTime + gap * 129, "J"),
					new BeatPlay(startTime + gap * 132, "L"), new BeatPlay(startTime + gap * 135, "S"),
					new BeatPlay(startTime + gap * 137, "S"), new BeatPlay(startTime + gap * 139, "K"),
					new BeatPlay(startTime + gap * 141, "L"), new BeatPlay(startTime + gap * 143, "D"),
					new BeatPlay(startTime + gap * 145, "J"), new BeatPlay(startTime + gap * 147, "F"),
					new BeatPlay(startTime + gap * 149, "S"), new BeatPlay(startTime + gap * 151, "L"),
					new BeatPlay(startTime + gap * 153, "F"), new BeatPlay(startTime + gap * 155, "D"),
					new BeatPlay(startTime + gap * 157, "J"), new BeatPlay(startTime + gap * 159, "K"),
					new BeatPlay(startTime + gap * 161, "S"), new BeatPlay(startTime + gap * 163, "L"),
					new BeatPlay(startTime + gap * 165, "J"), new BeatPlay(startTime + gap * 167, "S"),
					new BeatPlay(startTime + gap * 169, "F"), new BeatPlay(startTime + gap * 171, "J"),
					new BeatPlay(startTime + gap * 173, "D"), new BeatPlay(startTime + gap * 175, "K"),
					new BeatPlay(startTime + gap * 177, "D"), new BeatPlay(startTime + gap * 179, "K"),
					new BeatPlay(startTime + gap * 181, "L"), new BeatPlay(startTime + gap * 183, "S"),
					new BeatPlay(startTime + gap * 183, "K"), new BeatPlay(startTime + gap * 185, "F"),
					new BeatPlay(startTime + gap * 185, "S"), new BeatPlay(startTime + gap * 187, "S"),
					new BeatPlay(startTime + gap * 187, "L"), new BeatPlay(startTime + gap * 189, "F"),
					new BeatPlay(startTime + gap * 189, "L"), new BeatPlay(startTime + gap * 191, "D"),
					new BeatPlay(startTime + gap * 193, "J"), new BeatPlay(startTime + gap * 195, "L"),
					new BeatPlay(startTime + gap * 197, "J"), new BeatPlay(startTime + gap * 199, "L"),
					new BeatPlay(startTime + gap * 201, "F"), new BeatPlay(startTime + gap * 203, "D"),
					new BeatPlay(startTime + gap * 205, "K"), new BeatPlay(startTime + gap * 207, "D"),
					new BeatPlay(startTime + gap * 209, "K"), new BeatPlay(startTime + gap * 211, "J"),
					new BeatPlay(startTime + gap * 213, "S"), new BeatPlay(startTime + gap * 213, "F"),
					new BeatPlay(startTime + gap * 215, "D"), new BeatPlay(startTime + gap * 217, "K"),
					new BeatPlay(startTime + gap * 219, "L"), 
					new BeatPlay(startTime + gap * 222, "J"), new BeatPlay(startTime + gap * 222, "L"),
					new BeatPlay(startTime + gap * 224, "F"), new BeatPlay(startTime + gap * 226, "J"),
					new BeatPlay(startTime + gap * 228, "K"), new BeatPlay(startTime + gap * 228, "D"),
					new BeatPlay(startTime + gap * 230, "L"), 
					new BeatPlay(startTime + gap * 231, "S"), new BeatPlay(startTime + gap * 231, "F"),
					new BeatPlay(startTime + gap * 233, "F"), new BeatPlay(startTime + gap * 233, "K"),
					new BeatPlay(startTime + gap * 235, "S"), new BeatPlay(startTime + gap * 237, "L"),
					new BeatPlay(startTime + gap * 239, "D"), 
					new BeatPlay(startTime + gap * 240, "J"), new BeatPlay(startTime + gap * 240, "L"),
					new BeatPlay(startTime + gap * 242, "F"), new BeatPlay(startTime + gap * 244, "K"),
					new BeatPlay(startTime + gap * 246, "S"), new BeatPlay(startTime + gap * 248, "L"),
					new BeatPlay(startTime + gap * 249, "D"),
					new BeatPlay(startTime + gap * 251, "K"), new BeatPlay(startTime + gap * 253, "S"),
					new BeatPlay(startTime + gap * 255, "F"), new BeatPlay(startTime + gap * 255, "L"),
					new BeatPlay(startTime + gap * 257, "S"), new BeatPlay(startTime + gap * 257, "F"),
					new BeatPlay(startTime + gap * 259, "J"), new BeatPlay(startTime + gap * 261, "S"),
					new BeatPlay(startTime + gap * 263, "D"), new BeatPlay(startTime + gap * 265, "K"),
					new BeatPlay(startTime + gap * 266, "J"), new BeatPlay(startTime + gap * 266, "L"),
					new BeatPlay(startTime + gap * 268, "F"), new BeatPlay(startTime + gap * 268, "S"),
					new BeatPlay(startTime + gap * 270, "K"), new BeatPlay(startTime + gap * 270, "D"),
					new BeatPlay(startTime + gap * 272, "L"), new BeatPlay(startTime + gap * 274, "J"),
					new BeatPlay(startTime + gap * 275, "S"), new BeatPlay(startTime + gap * 275, "F"),
					new BeatPlay(startTime + gap * 277, "S"), new BeatPlay(startTime + gap * 279, "D"),
					new BeatPlay(startTime + gap * 281, "F"),
					new BeatPlay(startTime + gap * 284, "J"), new BeatPlay(startTime + gap * 284, "L"),
					new BeatPlay(startTime + gap * 286, "J"), new BeatPlay(startTime + gap * 288, "K"),
					new BeatPlay(startTime + gap * 290, "L"),
					new BeatPlay(startTime + gap * 293, "F"),
					new BeatPlay(startTime + gap * 295, "S"), new BeatPlay(startTime + gap * 295, "K"),
					new BeatPlay(startTime + gap * 297, "D"), new BeatPlay(startTime + gap * 299, "F"),
					new BeatPlay(startTime + gap * 299, "J"), new BeatPlay(startTime + gap * 301, "L"),
					new BeatPlay(startTime + gap * 302, "S"),
					new BeatPlay(startTime + gap * 304, "K"), new BeatPlay(startTime + gap * 306, "L"),
					new BeatPlay(startTime + gap * 308, "D"),
					new BeatPlay(startTime + gap * 311, "F"),
					new BeatPlay(startTime + gap * 313, "K"), new BeatPlay(startTime + gap * 315, "L"),
					new BeatPlay(startTime + gap * 317, "D"), new BeatPlay(startTime + gap * 319, "K"),
					new BeatPlay(startTime + gap * 320, "J"),
					new BeatPlay(startTime + gap * 322, "F"), new BeatPlay(startTime + gap * 324, "S"),
					new BeatPlay(startTime + gap * 326, "J"), new BeatPlay(startTime + gap * 328, "D"),
					new BeatPlay(startTime + gap * 329, "L"),
					new BeatPlay(startTime + gap * 331, "F"), new BeatPlay(startTime + gap * 333, "S"),
					new BeatPlay(startTime + gap * 335, "J"), new BeatPlay(startTime + gap * 337, "D"),
					new BeatPlay(startTime + gap * 338, "S"),
					new BeatPlay(startTime + gap * 340, "F"), new BeatPlay(startTime + gap * 340, "K"),
					new BeatPlay(startTime + gap * 342, "S"), new BeatPlay(startTime + gap * 342, "F"),
					new BeatPlay(startTime + gap * 344, "J"), new BeatPlay(startTime + gap * 346, "F"),
					new BeatPlay(startTime + gap * 347, "F"),
					new BeatPlay(startTime + gap * 349, "D"), new BeatPlay(startTime + gap * 351, "F"),
					new BeatPlay(startTime + gap * 353, "K"), new BeatPlay(startTime + gap * 355, "S"),
					new BeatPlay(startTime + gap * 356, "J"),
					new BeatPlay(startTime + gap * 358, "J"), new BeatPlay(startTime + gap * 360, "L"),
					new BeatPlay(startTime + gap * 362, "S"), new BeatPlay(startTime + gap * 364, "K"),
					new BeatPlay(startTime + gap * 365, "L"),
					new BeatPlay(startTime + gap * 367, "D"), new BeatPlay(startTime + gap * 367, "K"),
					new BeatPlay(startTime + gap * 369, "F"), new BeatPlay(startTime + gap * 369, "L"),
					new BeatPlay(startTime + gap * 371, "K"), new BeatPlay(startTime + gap * 371, "J"),
					new BeatPlay(startTime + gap * 373, "D"), new BeatPlay(startTime + gap * 374, "L"),
					new BeatPlay(startTime + gap * 376, "J"), new BeatPlay(startTime + gap * 378, "L"),
					new BeatPlay(startTime + gap * 380, "S"), new BeatPlay(startTime + gap * 382, "L"),
					new BeatPlay(startTime + gap * 383, "L"),
					new BeatPlay(startTime + gap * 385, "K"), new BeatPlay(startTime + gap * 387, "S"),
					new BeatPlay(startTime + gap * 389, "L"), new BeatPlay(startTime + gap * 391, "D"),
					new BeatPlay(startTime + gap * 392, "J"),
					new BeatPlay(startTime + gap * 394, "D"), new BeatPlay(startTime + gap * 396, "F"),
					new BeatPlay(startTime + gap * 398, "S"), new BeatPlay(startTime + gap * 400, "J"),
					new BeatPlay(startTime + gap * 401, "F"),
					new BeatPlay(startTime + gap * 403, "K"), new BeatPlay(startTime + gap * 405, "L"),
					new BeatPlay(startTime + gap * 407, "J"), new BeatPlay(startTime + gap * 409, "F"),
					new BeatPlay(startTime + gap * 410, "S"),
					new BeatPlay(startTime + gap * 412, "K"), new BeatPlay(startTime + gap * 414, "S"),
					new BeatPlay(startTime + gap * 416, "D"), new BeatPlay(startTime + gap * 418, "J"),
					new BeatPlay(startTime + gap * 419, "L"),
					new BeatPlay(startTime + gap * 421, "S"), new BeatPlay(startTime + gap * 423, "K"),
					new BeatPlay(startTime + gap * 425, "J"), new BeatPlay(startTime + gap * 427, "K"),
					new BeatPlay(startTime + gap * 428, "J"),
					new BeatPlay(startTime + gap * 430, "K"), new BeatPlay(startTime + gap * 430, "D"),
					new BeatPlay(startTime + gap * 432, "L"), new BeatPlay(startTime + gap * 432, "F"),
					new BeatPlay(startTime + gap * 434, "J"), new BeatPlay(startTime + gap * 434, "S"),
					new BeatPlay(startTime + gap * 436, "K"),
					new BeatPlay(startTime + gap * 437, "F"),
					new BeatPlay(startTime + gap * 439, "D"), new BeatPlay(startTime + gap * 441, "S"),
					new BeatPlay(startTime + gap * 443, "F"), new BeatPlay(startTime + gap * 445, "J"),
					new BeatPlay(startTime + gap * 446, "S"),
					new BeatPlay(startTime + gap * 448, "K"), new BeatPlay(startTime + gap * 450, "J"),
					new BeatPlay(startTime + gap * 452, "L"), new BeatPlay(startTime + gap * 454, "S"),
					new BeatPlay(startTime + gap * 455, "F"),
					new BeatPlay(startTime + gap * 457, "S"), new BeatPlay(startTime + gap * 459, "K"),
					new BeatPlay(startTime + gap * 461, "J"), new BeatPlay(startTime + gap * 463, "L"),
					new BeatPlay(startTime + gap * 464, "S"),
					new BeatPlay(startTime + gap * 466, "D"), new BeatPlay(startTime + gap * 468, "K"),
					new BeatPlay(startTime + gap * 470, "D"), new BeatPlay(startTime + gap * 472, "J"),
					new BeatPlay(startTime + gap * 473, "L"),
					new BeatPlay(startTime + gap * 475, "K"), new BeatPlay(startTime + gap * 477, "D"),
					new BeatPlay(startTime + gap * 479, "K"), new BeatPlay(startTime + gap * 481, "J"),
					new BeatPlay(startTime + gap * 482, "F"),
					new BeatPlay(startTime + gap * 484, "S"), new BeatPlay(startTime + gap * 486, "F"),
					new BeatPlay(startTime + gap * 488, "S"), new BeatPlay(startTime + gap * 490, "L"),
					new BeatPlay(startTime + gap * 491, "J"),
					new BeatPlay(startTime + gap * 493, "F"), new BeatPlay(startTime + gap * 495, "S"),
					new BeatPlay(startTime + gap * 497, "F"), new BeatPlay(startTime + gap * 499, "K"),
					new BeatPlay(startTime + gap * 500, "S"),
					new BeatPlay(startTime + gap * 502, "J"), new BeatPlay(startTime + gap * 504, "L"),
					new BeatPlay(startTime + gap * 506, "J"), new BeatPlay(startTime + gap * 508, "K"),
					new BeatPlay(startTime + gap * 509, "L"),
					new BeatPlay(startTime + gap * 511, "S"), new BeatPlay(startTime + gap * 513, "F"),
					new BeatPlay(startTime + gap * 515, "S"), new BeatPlay(startTime + gap * 517, "D"),
					new BeatPlay(startTime + gap * 518, "F"),
					new BeatPlay(startTime + gap * 520, "L"), new BeatPlay(startTime + gap * 522, "J"),
					new BeatPlay(startTime + gap * 524, "L"), new BeatPlay(startTime + gap * 526, "D"),
					new BeatPlay(startTime + gap * 527, "J"),
					new BeatPlay(startTime + gap * 529, "S"), new BeatPlay(startTime + gap * 531, "J"),
					new BeatPlay(startTime + gap * 533, "L"), new BeatPlay(startTime + gap * 524, "K"),
					new BeatPlay(startTime + gap * 536, "J"),
					new BeatPlay(startTime + gap * 538, "S"), new BeatPlay(startTime + gap * 538, "F"), new BeatPlay(startTime + gap * 538, "K"), 
					new BeatPlay(startTime + gap * 540, "D"),
					new BeatPlay(startTime + gap * 542, "J"), new BeatPlay(startTime + gap * 542, "L"), new BeatPlay(startTime + gap * 542, "D"), 
					new BeatPlay(startTime + gap * 544, "K"), new BeatPlay(startTime + gap * 545, "F"),
					new BeatPlay(startTime + gap * 547, "L"), new BeatPlay(startTime + gap * 549, "L"),
					new BeatPlay(startTime + gap * 551, "L"), new BeatPlay(startTime + gap * 553, "D"),
					new BeatPlay(startTime + gap * 554, "J"),
					new BeatPlay(startTime + gap * 557, "D"), new BeatPlay(startTime + gap * 559, "D"),
					new BeatPlay(startTime + gap * 561, "D"),
					new BeatPlay(startTime + gap * 563, "S"),
					new BeatPlay(startTime + gap * 565, "D"), new BeatPlay(startTime + gap * 567, "J"),
					new BeatPlay(startTime + gap * 569, "F"), new BeatPlay(startTime + gap * 571, "K"),
					new BeatPlay(startTime + gap * 572, "L"),
					new BeatPlay(startTime + gap * 574, "K"), new BeatPlay(startTime + gap * 576, "S"),
					new BeatPlay(startTime + gap * 578, "D"), new BeatPlay(startTime + gap * 580, "L"),
					new BeatPlay(startTime + gap * 581, "F"),
					new BeatPlay(startTime + gap * 583, "D"), new BeatPlay(startTime + gap * 585, "F"),
					new BeatPlay(startTime + gap * 587, "J"), new BeatPlay(startTime + gap * 589, "S"),
					new BeatPlay(startTime + gap * 590, "J"),
					new BeatPlay(startTime + gap * 592, "D"), new BeatPlay(startTime + gap * 594, "J"),
					new BeatPlay(startTime + gap * 596, "S"), new BeatPlay(startTime + gap * 598, "K"),
					new BeatPlay(startTime + gap * 599, "S"),
					new BeatPlay(startTime + gap * 601, "S"), new BeatPlay(startTime + gap * 601, "F"),
					new BeatPlay(startTime + gap * 603, "S"), new BeatPlay(startTime + gap * 603, "K"),
					new BeatPlay(startTime + gap * 605, "S"), new BeatPlay(startTime + gap * 605, "L"),
					new BeatPlay(startTime + gap * 607, "D"), new BeatPlay(startTime + gap * 608, "L"),
					};
			return beats;

		}

		return null;
	}

	public BeatPlay[] harmony(String difficulty) {
		int startTime = 300 - Main.REACH_TIME * 1000;
		int gap = 350;
		int gap2 = 200;
		if (difficulty.equals("Easy")) {
			beats = new BeatPlay[] { 
					new BeatPlay(startTime, "L"), new BeatPlay(startTime + gap * 1, "L"),
					new BeatPlay(startTime + gap * 2, "D"), new BeatPlay(startTime + gap * 6, "S"),
					new BeatPlay(startTime + gap * 7, "L"), new BeatPlay(startTime + gap * 10, "K"),
					new BeatPlay(startTime + gap * 12, "L"), new BeatPlay(startTime + gap * 14, "J"),
					new BeatPlay(startTime + gap * 16, "L"), new BeatPlay(startTime + gap * 18, "F"),
					new BeatPlay(startTime + gap * 20, "L"), new BeatPlay(startTime + gap * 22, "F"),
					new BeatPlay(startTime + gap * 24, "L"), new BeatPlay(startTime + gap * 26, "K"),
					new BeatPlay(startTime + gap * 28, "L"), new BeatPlay(startTime + gap * 30, "J"),
					new BeatPlay(startTime + gap * 32, "L"), new BeatPlay(startTime + gap * 34, "K"),
					new BeatPlay(startTime + gap * 38, "L"), new BeatPlay(startTime + gap * 40, "J"),
					new BeatPlay(startTime + gap * 42, "K"), new BeatPlay(startTime + gap * 43, "J"),
					new BeatPlay(startTime + gap * 44, "F"), new BeatPlay(startTime + gap * 45, "D"),
					new BeatPlay(startTime + gap * 45, "S"), new BeatPlay(startTime + gap * 47, "L"),
					new BeatPlay(startTime + gap * 49, "J"), new BeatPlay(startTime + gap * 55, "L"),
					new BeatPlay(startTime + gap * 58, "K"), new BeatPlay(startTime + gap * 65, "L"),
					new BeatPlay(startTime + gap * 67, "K"), new BeatPlay(startTime + gap * 67, "D"),
					new BeatPlay(startTime + gap * 73, "D"), new BeatPlay(startTime + gap * 75, "K"),
					new BeatPlay(startTime + gap * 76, "D"), new BeatPlay(startTime + gap * 78, "K"),
					new BeatPlay(startTime + gap * 79, "K"), new BeatPlay(startTime + gap * 80, "J"),
					new BeatPlay(startTime + gap * 81, "L"), new BeatPlay(startTime + gap * 82, "S"),
					new BeatPlay(startTime + gap * 84, "K"), new BeatPlay(startTime + gap * 87, "K"),
					new BeatPlay(startTime + gap * 88, "L"), new BeatPlay(startTime + gap * 89, "J"),
					new BeatPlay(startTime + gap * 90, "J"), new BeatPlay(startTime + gap * 91, "K"),
					new BeatPlay(startTime + gap * 92, "J"), new BeatPlay(startTime + gap * 93, "D"),
					new BeatPlay(startTime + gap * 95, "K"), new BeatPlay(startTime + gap * 96, "D"),
					new BeatPlay(startTime + gap * 99, "K"), new BeatPlay(startTime + gap * 100, "J"),
					new BeatPlay(startTime + gap * 101, "S"), new BeatPlay(startTime + gap * 102, "K"),
					new BeatPlay(startTime + gap * 103, "L"), new BeatPlay(startTime + gap * 104, "L"),
					new BeatPlay(startTime + gap * 106, "J"), new BeatPlay(startTime + gap * 107, "K"),
					new BeatPlay(startTime + gap * 108, "L"), new BeatPlay(startTime + gap * 109, "L"),
					new BeatPlay(startTime + gap * 110, "J"), new BeatPlay(startTime + gap * 111, "D"),
					new BeatPlay(startTime + gap * 113, "K"), new BeatPlay(startTime + gap * 114, "D"),
					new BeatPlay(startTime + gap * 116, "K"), new BeatPlay(startTime + gap * 117, "K"),
					new BeatPlay(startTime + gap * 118, "J"), new BeatPlay(startTime + gap * 119, "D"),
					new BeatPlay(startTime + gap * 121, "S"), new BeatPlay(startTime + gap * 123, "K"),
					new BeatPlay(startTime + gap * 124, "S"), new BeatPlay(startTime + gap * 126, "K"),
					new BeatPlay(startTime + gap * 127, "L"), new BeatPlay(startTime + gap * 128, "J"),
					new BeatPlay(startTime + gap * 129, "J"), new BeatPlay(startTime + gap * 130, "K"),
					new BeatPlay(startTime + gap * 130, "L"), new BeatPlay(startTime + gap * 131, "D"),
					new BeatPlay(startTime + gap * 133, "K"), new BeatPlay(startTime + gap * 134, "D"),
					new BeatPlay(startTime + gap * 136, "K"), new BeatPlay(startTime + gap * 137, "K"),
					new BeatPlay(startTime + gap * 138, "J"), new BeatPlay(startTime + gap * 139, "L"),
					new BeatPlay(startTime + gap * 140, "J"), // 50
					new BeatPlay(startTime + gap * 141, "K"), new BeatPlay(startTime + gap * 142, "L"),
					new BeatPlay(startTime + gap * 143, "L"), new BeatPlay(startTime + gap * 144, "J"),
					new BeatPlay(startTime + gap * 145, "K"), new BeatPlay(startTime + gap * 146, "L"),
					new BeatPlay(startTime + gap * 147, "J"), new BeatPlay(startTime + gap * 148, "D"),
					new BeatPlay(startTime + gap * 149, "L"), new BeatPlay(startTime + gap * 152, "L"), // 60
					new BeatPlay(startTime + gap * 154, "L"), new BeatPlay(startTime + gap * 156, "J"),
					new BeatPlay(startTime + gap * 158, "J"), new BeatPlay(startTime + gap * 160, "F"),
					new BeatPlay(startTime + gap * 162, "F"), new BeatPlay(startTime + gap * 163, "J"),
					new BeatPlay(startTime + gap * 165, "J"), new BeatPlay(startTime + gap * 169, "L"),
					new BeatPlay(startTime + gap * 170, "L"), new BeatPlay(startTime + gap * 171, "J"),
					new BeatPlay(startTime + gap * 173, "J"),  };
			return beats;
		}
		else if (difficulty.equals("Hard")) {
			beats = new BeatPlay[] { 
					new BeatPlay(startTime, "L"), new BeatPlay(startTime + gap * 1, "L"),
					new BeatPlay(startTime + gap * 1, "J"), new BeatPlay(startTime + gap * 2, "D"),
					new BeatPlay(startTime + gap * 2, "F"), new BeatPlay(startTime + gap * 2, "S"),
					new BeatPlay(startTime + gap * 6, "L"), new BeatPlay(startTime + gap * 6, "D"),
					new BeatPlay(startTime + gap * 7, "L"), new BeatPlay(startTime + gap * 7, "S"),
					new BeatPlay(startTime + gap * 9, "L"), new BeatPlay(startTime + gap * 9, "F"),
					new BeatPlay(startTime + gap * 10, "J"), new BeatPlay(startTime + gap * 10, "F"),
					new BeatPlay(startTime + gap * 12, "L"), new BeatPlay(startTime + gap * 12, "K"),
					new BeatPlay(startTime + gap * 13, "L"), new BeatPlay(startTime + gap * 13, "S"),
					new BeatPlay(startTime + gap * 14, "J"), new BeatPlay(startTime + gap * 14, "F"),
					new BeatPlay(startTime + gap * 16, "L"), new BeatPlay(startTime + gap * 16, "K"),
					new BeatPlay(startTime + gap * 17, "L"), new BeatPlay(startTime + gap * 17, "J"),
					new BeatPlay(startTime + gap * 18, "F"), new BeatPlay(startTime + gap * 18, "S"),
					new BeatPlay(startTime + gap * 20, "L"), new BeatPlay(startTime + gap * 20, "K"),
					new BeatPlay(startTime + gap * 21, "L"), new BeatPlay(startTime + gap * 21, "J"),
					new BeatPlay(startTime + gap * 22, "F"), new BeatPlay(startTime + gap * 22, "K"),
					new BeatPlay(startTime + gap * 24, "L"), new BeatPlay(startTime + gap * 25, "L"),
					new BeatPlay(startTime + gap * 26, "K"), new BeatPlay(startTime + gap * 26, "D"),
					new BeatPlay(startTime + gap * 28, "L"), new BeatPlay(startTime + gap * 29, "L"),
					new BeatPlay(startTime + gap * 29, "K"), 
					new BeatPlay(startTime + gap * 30, "J"), new BeatPlay(startTime + gap * 30, "D"), 
					new BeatPlay(startTime + gap * 32, "L"),
					new BeatPlay(startTime + gap * 33, "L"), 
					new BeatPlay(startTime + gap * 34, "K"), new BeatPlay(startTime + gap * 34, "F"), // hard
					new BeatPlay(startTime + gap * 38, "L"), new BeatPlay(startTime + gap * 39, "L"),
					new BeatPlay(startTime + gap * 39, "K"), new BeatPlay(startTime + gap * 40, "J"),
					new BeatPlay(startTime + gap * 40, "S"), new BeatPlay(startTime + gap2 * 40, "K"),
					new BeatPlay(startTime + gap2 * 41, "J"), new BeatPlay(startTime + gap2 * 42, "F"),
					new BeatPlay(startTime + gap * 42, "K"), new BeatPlay(startTime + gap2 * 43, "D"),
					new BeatPlay(startTime + gap * 43, "J"), new BeatPlay(startTime + gap * 44, "F"),
					new BeatPlay(startTime + gap * 45, "D"), new BeatPlay(startTime + gap * 45, "S"),
					new BeatPlay(startTime + gap * 47, "L"), 
					new BeatPlay(startTime + gap * 48, "L"), new BeatPlay(startTime + gap * 48, "K"), 
					new BeatPlay(startTime + gap * 49, "J"), new BeatPlay(startTime + gap * 49, "D"), 
					new BeatPlay(startTime + gap * 55, "L"),
					new BeatPlay(startTime + gap * 57, "L"), new BeatPlay(startTime + gap * 57, "K"),
					new BeatPlay(startTime + gap * 58, "J"), new BeatPlay(startTime + gap * 58, "D"),
					new BeatPlay(startTime + gap * 65, "L"), new BeatPlay(startTime + gap * 65, "K"),
					new BeatPlay(startTime + gap * 66, "L"), 
					new BeatPlay(startTime + gap * 67, "K"), new BeatPlay(startTime + gap * 67, "D"), new BeatPlay(startTime + gap * 67, "S"),
					new BeatPlay(startTime + gap * 73, "D"), 
					new BeatPlay(startTime + gap * 74, "K"), new BeatPlay(startTime + gap * 74, "S"), 
					new BeatPlay(startTime + gap * 75, "K"), new BeatPlay(startTime + gap * 75, "D"), 
					new BeatPlay(startTime + gap * 76, "D"),
					new BeatPlay(startTime + gap * 77, "K"), new BeatPlay(startTime + gap * 77, "L"),
					new BeatPlay(startTime + gap * 78, "K"), new BeatPlay(startTime + gap * 78, "D"),
					new BeatPlay(startTime + gap * 79, "K"), 
					new BeatPlay(startTime + gap * 80, "J"), new BeatPlay(startTime + gap * 80, "F"), 
					new BeatPlay(startTime + gap * 81, "L"),
					new BeatPlay(startTime + gap * 82, "S"), 
					new BeatPlay(startTime + gap * 83, "K"), new BeatPlay(startTime + gap * 83, "S"), 
					new BeatPlay(startTime + gap * 84, "K"), new BeatPlay(startTime + gap * 84, "D"), 
					new BeatPlay(startTime + gap * 85, "S"),
					new BeatPlay(startTime + gap * 86, "K"), new BeatPlay(startTime + gap * 86, "F"),
					new BeatPlay(startTime + gap * 87, "K"), new BeatPlay(startTime + gap * 87, "J"),
					new BeatPlay(startTime + gap * 88, "L"), new BeatPlay(startTime + gap * 89, "J"),
					new BeatPlay(startTime + gap * 89, "F"), new BeatPlay(startTime + gap * 90, "J"),
					new BeatPlay(startTime + gap * 90, "F"), new BeatPlay(startTime + gap * 91, "K"),
					new BeatPlay(startTime + gap * 92, "J"), new BeatPlay(startTime + gap * 93, "D"),
					new BeatPlay(startTime + gap * 94, "K"), new BeatPlay(startTime + gap * 94, "L"),
					new BeatPlay(startTime + gap * 95, "K"), new BeatPlay(startTime + gap * 95, "S"),
					new BeatPlay(startTime + gap * 96, "D"), 
					new BeatPlay(startTime + gap * 97, "K"), new BeatPlay(startTime + gap * 97, "S"), 
					new BeatPlay(startTime + gap * 98, "K"), new BeatPlay(startTime + gap * 98, "J"), // HARD
					new BeatPlay(startTime + gap * 99, "K"), new BeatPlay(startTime + gap * 100, "J"),
					new BeatPlay(startTime + gap * 101, "D"), new BeatPlay(startTime + gap * 102, "K"),
					new BeatPlay(startTime + gap * 103, "L"), new BeatPlay(startTime + gap * 103, "S"),
					new BeatPlay(startTime + gap * 104, "L"), new BeatPlay(startTime + gap * 104, "D"),
					new BeatPlay(startTime + gap * 106, "J"), new BeatPlay(startTime + gap * 107, "K"),
					new BeatPlay(startTime + gap * 108, "L"), new BeatPlay(startTime + gap * 109, "L"),
					new BeatPlay(startTime + gap * 110, "K"), new BeatPlay(startTime + gap * 110, "J"),
					new BeatPlay(startTime + gap * 111, "D"), new BeatPlay(startTime + gap * 111, "S"),
					new BeatPlay(startTime + gap * 112, "K"), new BeatPlay(startTime + gap * 112, "D"),
					new BeatPlay(startTime + gap * 113, "K"), new BeatPlay(startTime + gap * 113, "J"),
					new BeatPlay(startTime + gap * 114, "D"), new BeatPlay(startTime + gap * 114, "S"),
					new BeatPlay(startTime + gap * 115, "S"), new BeatPlay(startTime + gap * 115, "K"),
					new BeatPlay(startTime + gap * 116, "K"), new BeatPlay(startTime + gap * 116, "D"),
					new BeatPlay(startTime + gap * 117, "K"), new BeatPlay(startTime + gap * 118, "J"),
					new BeatPlay(startTime + gap * 119, "D"), new BeatPlay(startTime + gap * 121, "S"),
					new BeatPlay(startTime + gap * 122, "K"), new BeatPlay(startTime + gap * 122, "D"),
					new BeatPlay(startTime + gap * 123, "K"), new BeatPlay(startTime + gap * 123, "J"),
					new BeatPlay(startTime + gap * 124, "S"), new BeatPlay(startTime + gap * 125, "K"),
					new BeatPlay(startTime + gap * 125, "J"), 
					new BeatPlay(startTime + gap * 126, "K"), new BeatPlay(startTime + gap * 126, "S"), // Hard
					new BeatPlay(startTime + gap * 127, "L"), new BeatPlay(startTime + gap * 127, "S"),
					new BeatPlay(startTime + gap * 128, "J"), new BeatPlay(startTime + gap * 128, "K"),
					new BeatPlay(startTime + gap * 129, "J"), new BeatPlay(startTime + gap * 129, "K"),
					new BeatPlay(startTime + gap * 130, "K"), new BeatPlay(startTime + gap * 130, "D"), new BeatPlay(startTime + gap * 130, "L"), 
					new BeatPlay(startTime + gap * 131, "D"), new BeatPlay(startTime + gap * 131, "S"), 
					new BeatPlay(startTime + gap * 132, "K"), new BeatPlay(startTime + gap * 132, "S"), 
					new BeatPlay(startTime + gap * 133, "K"), new BeatPlay(startTime + gap * 133, "F"), 
					new BeatPlay(startTime + gap * 134, "D"),
					new BeatPlay(startTime + gap * 135, "K"), new BeatPlay(startTime + gap * 135, "F"),
					new BeatPlay(startTime + gap * 136, "K"), new BeatPlay(startTime + gap * 136, "F"),
					new BeatPlay(startTime + gap * 137, "K"), new BeatPlay(startTime + gap * 137, "J"),
					new BeatPlay(startTime + gap * 138, "D"), new BeatPlay(startTime + gap * 138, "S"),
					new BeatPlay(startTime + gap * 139, "F"), new BeatPlay(startTime + gap * 140, "J"), // 50
					new BeatPlay(startTime + gap * 140, "K"), new BeatPlay(startTime + gap * 141, "K"),
					new BeatPlay(startTime + gap * 142, "L"), new BeatPlay(startTime + gap * 142, "D"),
					new BeatPlay(startTime + gap * 143, "L"), new BeatPlay(startTime + gap * 143, "S"),
					new BeatPlay(startTime + gap * 144, "J"), new BeatPlay(startTime + gap * 144, "K"),
					new BeatPlay(startTime + gap * 145, "K"), 
					new BeatPlay(startTime + gap * 146, "L"), new BeatPlay(startTime + gap * 146, "F"), 
					new BeatPlay(startTime + gap * 147, "J"),
					new BeatPlay(startTime + gap * 148, "J"), 
					new BeatPlay(startTime + gap * 149, "L"), new BeatPlay(startTime + gap * 149, "S"), 
					new BeatPlay(startTime + gap * 152, "L"), // hard UNDER
					new BeatPlay(startTime + gap * 154, "L"), new BeatPlay(startTime + gap * 156, "J"),
					new BeatPlay(startTime + gap * 157, "J"), new BeatPlay(startTime + gap * 158, "J"),
					new BeatPlay(startTime + gap * 159, "J"), new BeatPlay(startTime + gap * 160, "F"),
					new BeatPlay(startTime + gap * 162, "F"), new BeatPlay(startTime + gap * 163, "J"),
					new BeatPlay(startTime + gap * 164, "J"), new BeatPlay(startTime + gap * 165, "J"),
					new BeatPlay(startTime + gap * 166, "J"), new BeatPlay(startTime + gap * 169, "L"),
					new BeatPlay(startTime + gap * 170, "L"), new BeatPlay(startTime + gap * 171, "J"),
					new BeatPlay(startTime + gap * 172, "J"), new BeatPlay(startTime + gap * 173, "J"),
					};
			return beats;
		}
		
		return null;
	}
	
}
